name: "38-gh-pages-deploy-frontend — Deploy to GitHub Pages"
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    # - name: Checkout local code
    #   uses: actions/checkout@v2

    - name: Debug Env Variables
      run:
        echo "DOCS_SOURCE_REPO=${{vars.DOCS_SOURCE_REPO}}"
        echo "github.repository=${{github.repository}}"

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: 'ucsb-cs156-s23/STARTER-team01'
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    
    - name: Install NPM packages
      run: npm ci
      working-directory: ./frontend

    - name: Build Storybook
      working-directory: ./frontend
      run: | # Install npm packages and build the Storybook files
        npx build-storybook --docs
        echo "DOCS_SOURCE_REPO=${{vars.DOCS_SOURCE_REPO}}"
        echo "github.repository=${{github.repository}}"
        
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: ./frontend/storybook-static # The folder the action should deploy.
        branch: gh-pages
